---

apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: staging
  namespace: default
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: staging
  source:
    repoURL: https://github.com/Khaalidsub/kubernetes-cluster.git
    targetRevision: HEAD
    path: minifest/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
