apiVersion: argoproj.io/v1alpha1
kind: Sensor
metadata:
  name: webhook
spec:
  template:
    container:
      volumeMounts:
        - mountPath: /workflows/staging.yml
          name: staging-workflow
    volumes:
      - name: staging-workflow
        configMap:
          name: stagin-workflow-configmap
  dependencies:
    - name: test-dep
      eventSourceName: webhook
      eventName: example
  triggers:
    - template:
        name: webhook-workflow-trigger
        k8s:
          group: argoproj.io
          version: v1alpha1
          resource: workflows
          operation: create
          source:
           path: /workflows/staging.yml