apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: self-signed-certficate
spec:
  secretName: self-signed
  dnsNames:
  - "*.svc.cluster.local"
  - "*"
  issuerRef:
    name:  selfsigned-cluster-issuer